<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                
                'email_um6p' => 'Chaimae.AIDOUNI@um6p.ma',
                'health_insurance_number' => '9180941',
                'cin' => 'Q359565',
                'age' => 23,
                'date_naissance' => null,
                'ville' => 'Khouribga',
                'etudes' => 'Big data',
                'telephone' => '603664294',
            ],
            [
          
                'email_um6p' => 'Abdellatif.AITLAHNITE@um6p.ma',
                'health_insurance_number' => '9180948',
                'cin' => 'JC619709',
                'age' => 25,
                'date_naissance' => '2000-12-11',
                'ville' => 'El Jadida',
                'etudes' => 'Littérature anglaise',
                'telephone' => '603166719',
            ],
            [
                              'email_um6p' => 'Jihane.ATLASSI@um6p.ma',
                'health_insurance_number' => '9180953',
                'cin' => 'UY803904',
                'age' => 23,
                'date_naissance' => '2002-04-27',
                'ville' => 'Rabat',
                'etudes' => 'Communication & marketing',
                'telephone' => '6466839568',
            ],
            [
                               'email_um6p' => 'Badreddine.LGHALI@um6p.ma',
                'health_insurance_number' => '9180955',
                'cin' => 'D678410',
                'age' => 18,
                'date_naissance' => '2007-05-17',
                'ville' => 'Meknès',
                'etudes' => 'Langues, Littératures et cultures étrangères',
                'telephone' => '664387327',
            ],
            [
                            'email_um6p' => 'Khaoula.BARDI@um6p.ma',
                'health_insurance_number' => '9180939',
                'cin' => 'HA232681',
                'age' => 23,
                'date_naissance' => '2002-10-20',
                'ville' => 'Youssoufia',
                'etudes' => 'Sociologie',
                'telephone' => '609286983',
            ],
            [
                            'email_um6p' => 'Imane.BELHAMI@um6p.ma',
                'health_insurance_number' => '9180943',
                'cin' => 'J558630',
                'age' => 24,
                'date_naissance' => '2001-10-16',
                'ville' => 'Rabat',
                'etudes' => 'Architecture',
                'telephone' => '630070665',
            ],
            [
                               'email_um6p' => 'Jihane.BOUHSEN@um6p.ma',
                'health_insurance_number' => '9180952',
                'cin' => 'A445361',
                'age' => 30,
                'date_naissance' => '1995-06-10',
                'ville' => 'Rabat',
                'etudes' => 'Chimie',
                'telephone' => '668661162',
            ],
            [
                           'email_um6p' => 'Sami.CHAKOUR@um6p.ma',
                'health_insurance_number' => '9180945',
                'cin' => 'AE237265',
                'age' => 26,
                'date_naissance' => '1999-12-30',
                'ville' => 'Rabat',
                'etudes' => 'Psychologie',
                'telephone' => '623053021',
            ],
            [
                               'email_um6p' => 'Taha.ELHOUMAM@um6p.ma',
                'health_insurance_number' => '9180940',
                'cin' => 'CD705264',
                'age' => 22,
                'date_naissance' => '2003-07-10',
                'ville' => 'Fes',
                'etudes' => 'Littérature anglaise',
                'telephone' => '695236354',
            ],
            [
                            'email_um6p' => 'Ayoub.ESSAYEB@um6p.ma',
                'health_insurance_number' => '9180935',
                'cin' => 'AE303770',
                'age' => 23,
                'date_naissance' => '2002-06-27',
                'ville' => 'Salé',
                'etudes' => 'Psychologie',
                'telephone' => '682017382',
            ],
            [
                
                'email_um6p' => 'Karima.ESSIMMOU@um6p.ma',
                'health_insurance_number' => '9180949',
                'cin' => 'EE936812',
                'age' => 24,
                'date_naissance' => '2001-10-06',
                'ville' => 'Marrakesh',
                'etudes' => 'Commerce international',
                'telephone' => '632158214',
            ],
            [
                            'email_um6p' => 'Safia.KAAKOUA@um6p.ma',
                'health_insurance_number' => '9180947',
                'cin' => 'EE658895',
                'age' => 24,
                'date_naissance' => '2001-04-07',
                'ville' => 'Marrakech/Casablanca',
                'etudes' => 'Design intérieur',
                'telephone' => '636725197',
            ],
            [
                               'email_um6p' => 'FatimaZahra.KODSSI@um6p.ma',
                'health_insurance_number' => '9180937',
                'cin' => 'GI5620',
                'age' => 24,
                'date_naissance' => '2001-06-28',
                'ville' => 'Ifrane/Kénitra',
                'etudes' => 'Media and communication',
                'telephone' => '617949337',
            ],
            [
                          'email_um6p' => 'Safaa.KOTBI@um6p.ma',
                'health_insurance_number' => '9180946',
                'cin' => 'CE902605',
                'age' => 30,
                'date_naissance' => '1995-10-16',
                'ville' => 'Casablanca',
                'etudes' => 'Art',
                'telephone' => '671332762',
            ],
            [
                            'email_um6p' => 'Houssam.MADHA@um6p.ma',
                'health_insurance_number' => '9180951',
                'cin' => 'EE602231',
                'age' => 31,
                'date_naissance' => '1994-09-11',
                'ville' => 'Marrakech',
                'etudes' => 'Marketing Stratégique et Communication',
                'telephone' => '645161359',
            ],
            [
  
                'email_um6p' => 'FatimaAzzahrae.MAHROUG@um6p.ma',
                'health_insurance_number' => '9180954',
                'cin' => 'T329422',
                'age' => 22,
                'date_naissance' => '2003-11-15',
                'ville' => 'Casablanca',
                'etudes' => 'Physique',
                'telephone' => '664607212',
            ],
            [
                            'email_um6p' => 'Amina.MAMOUNI@um6p.ma',
                'health_insurance_number' => '9180938',
                'cin' => 'BL165791',
                'age' => 21,
                'date_naissance' => '2004-03-19',
                'ville' => 'Casablanca',
                'etudes' => 'Littérature anglaise',
                'telephone' => '687471536',
            ],
            [
    
                'email_um6p' => 'Yasmine.MESSAOUDI@um6p.ma',
                'health_insurance_number' => '9180942',
                'cin' => 'R360922',
                'age' => 28,
                'date_naissance' => '1997-10-20',
                'ville' => 'Al Hoceima',
                'etudes' => 'Culture et média',
                'telephone' => '611011929',
            ],
            [
                           'email_um6p' => 'Ikram.SADRAI@um6p.ma',
                'health_insurance_number' => '9180944',
                'cin' => 'Q371493',
                'age' => 21,
                'date_naissance' => '2004-08-12',
                'ville' => 'Khouribga',
                'etudes' => 'Web development',
                'telephone' => '635145879',
            ],
            [
                           'email_um6p' => 'Ghita.SOUMHI@um6p.ma',
                'health_insurance_number' => '9180936',
                'cin' => 'EE901823',
                'age' => 25,
                'date_naissance' => '2000-06-30',
                'ville' => 'Dubai/Marrakech',
                'etudes' => 'Ressources humaines',
                'telephone' => '971508525414',
            ],
            [
                           'email_um6p' => 'Ayman.STITOU@um6p.ma',
                'health_insurance_number' => '9180933',
                'cin' => 'KB191890',
                'age' => 25,
                'date_naissance' => '2000-07-26',
                'ville' => 'Tanger',
                'etudes' => 'Ingénierie et management de l\'innovation technologique',
                'telephone' => '655326685',
            ],
            [
                                'email_um6p' => 'Hubert.VOWOGBE@um6p.ma',
                'health_insurance_number' => '9180934',
                'cin' => '1B08709M',
                'age' => 27,
                'date_naissance' => '1996-03-11',
                'ville' => 'Rabat',
                'etudes' => 'Ingénierie civile',
                'telephone' => '707989091',
            ],
            [
                            'email_um6p' => 'Assia.ZOUHOUM@um6p.ma',
                'health_insurance_number' => '9180950',
                'cin' => 'JC638027',
                'age' => 23,
                'date_naissance' => '2002-07-17',
                'ville' => 'Rabat',
                'etudes' => 'Droit et science po',
                'telephone' => '762629647',
            ],
        ];

        DB::table('students')->insert($students);
    }
}
